spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.166:8848
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: user-service-route
          uri:
            lb://ujsoj-backend-user-service
          predicates:
            - Path=/api/user/**

        - id: judge-service-route
          uri:
            lb://ujsoj-backend-judge-service
          predicates:
            - Path=/api/judge/**

        - id: question-service-route
          uri:
            lb://ujsoj-backend-question-service
          predicates:
            - Path=/api/question/**

  application:
    name: ujsoj-backend-gateway
  main:
    web-application-type: reactive

server:
  port: 8100

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
